name: Mirror Docker Hub to GHCR

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and push
        run: |
          echo "⬇ Скачиваем из Docker Hub..."
          docker pull nasdorm/moex_predict:latest
          
          echo " Подготавливаем для GitHub Packages..."
          docker tag nasdorm/moex_predict:latest ghcr.io/nasdorm/moex_predict:latest
          
          echo "⬆ Загружаем в GitHub Packages..."
          docker push ghcr.io/nasdorm/moex_predict:latest
          
          echo " Готово! Образ доступен по адресу:"
          echo "ghcr.io/nasdorm/moex_predict:latest" 
