name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0'  # Каждое воскресенье
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
      
      - name: Install pip-tools
        run: pip install pip-tools
      
      - name: Update dependencies
        run: |
          pip-compile --upgrade requirements.in -o requirements.txt
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: 'chore: update dependencies'
          body: 'Automated dependency updates'
          branch: 'deps/update'